add images and content for workflow user-task assignments
pipeforce/pipeforce.github.io pull request #3
Opened 2022-03-01 16:15 UTC by mujtabafaizi

2022-03-02 05:40 UTC, sniederm requested changes

2022-03-02 05:40 UTC, sniederm commented on docs/guides/workflows/010_basics.md
> +Assignee: Username
This I dont understand. Why in this format? Isn't it just the username required here. Or separated by comma in case of multiple users. There is no prefix "Assignee:" required, right?

The same for Candidate User and Candidate Group.

2022-03-07 12:12 UTC, simonochs requested changes
See comment of Stephan

2022-03-07 15:09 UTC, mujtabafaizi commented on docs/guides/workflows/010_basics.md
> +Assignee: Username
please review latest update

2022-03-07 15:09 UTC, closed without merging